import { Inter } from 'next/font/google'
import './globals.css'
// import Navbar from '@/components/shared/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className='container mx-auto' lang="en">
      {/* <Navbar /> */}
      <body className={inter.className}>{children}</body>
    </html>
  )
}
